$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  type: console
  level: info
  batch_size: 100
  flush_interval: 2
  max_queue_size: 2048
  http_endpoint:
  http_headers:
  http_timeout: 5

mcp:
  servers:
    curl:
      command: "npx"
      args:
        [
#          "C:\\Program Files\\nodejs\\node_modules\\@mcp-get-community\\server-curl\\dist\\index.js",
          "-y"
          "@mcp-get-community/server-curl"
        ]
    filesystem:
      command: "npx"
      args:
        [
 #         "C:\\Program Files\\nodejs\\node_modules\\@modelcontextprotocol\\server-filesystem\\dist\\index.js",
          "-y"
          "@modelcontextprotocol/server-filesystem"
        ]

openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
  default_model: gpt-4o
