execution_engine: asyncio
logger:
  transports: [console, file]
  level: info
  show_progress: true
  path: "logs/github-to-slack.jsonl"
  path_settings:
    path_pattern: "logs/github-to-slack-{unique_id}.jsonl"
    unique_id: "timestamp"
    timestamp_format: "%Y%m%d_%H%M%S"

mcp:
  servers:
    github:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-github"]
      description: "Access GitHub API operations"
    slack:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-slack"]
      description: "Access Slack API operations"
