$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  type: console
  level: debug
  batch_size: 100
  flush_interval: 2
  max_queue_size: 2048
  http_endpoint:
  http_headers:
  http_timeout: 5
  progress_display: false

mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "."]
    firebase-mcp:
      command: "npx"
      args: ["-y", "@gannonh/firebase-mcp"]
 env:
        SERVICE_ACCOUNT_KEY_PATH: "./serviceAccountKey.json"  # Relative path
        FIREBASE_STORAGE_BUCKET: "${FIREBASE_STORAGE_BUCKET}"
        NODE_PATH: "/usr/local/lib/node_modules" # From secrets

openai:
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
  default_model: gpt-4o
