$schema: ../../schema/mcp-agent.config.schema.json

execution_engine: asyncio
logger:
  type: console
  level: debug

mcp:
  servers:
    root-test:
      command: "uv"
      args: ["run", "root_test_server.py"]
